name: 'Auth0 Server'
description: 'Auth0 CICD Example with Github Actions'
inputs:
  sls-version:
    description: 'Serverless Framework Version'
    required: true
  stage:
      description: 'Deployment Env'
      required: true
outputs:
  version:
    description: 'Deploying Node Server'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    STAGE: ${{ inputs.stage }}
    SLS_VERSION: ${{ inputs.sls-version }}